[package]
name = "wcdb_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
wcdb_core = { path = "../wcdb_core" }
table_binding = { path = "../table_binding" }

[[example]]
name = "demo"
path = "example/main.rs"
