[package]
name = "wcdb_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
wcdb_core = { path = "../wcdb_core" }
table_coding = { path = "../table_coding" }
once_cell = "1.8.0"
lazy_static = "1.5.0"

[dev-dependencies]
rand = "0.8.5"

[[example]]
name = "demo"
path = "example/main.rs"
