[package]
name = "wcdb_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
table_binding_derive = { path = "../table_binding_derive" }

[build-dependencies]
num_cpus = "1.16.0"
cmake = "0.1.52"

[[example]]
name = "demo"
path = "example/main.rs"
