image: "harbor.rongcloud.net/library/rust/wcdb:0.0.4"

variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/CargoHome

cache:
  paths:
    - CargoHome/registry/index/
    - CargoHome/registry/cache/

stages:
  - test

variables:
  GIT_DEPTH: 1

run_test:
  stage: test
  before_script:
    - git submodule update --init sqlcipher zstd
  script:
    - export CC=clang
    - export CXX=clang++
    - export RUSTC_WRAPPER=sccache
    - export RUSTFLAGS="-D warnings -A unused -A deprecated"
    - cd src/rust
    - autocorrect --lint
    - cargo fmt -- --check
    - cargo build
    - cargo run --package wcdb_rust --example demo
