image: "harbor.rongcloud.net/library/rust/wcdb:0.1.4"

cache:
  paths:
    - CargoHome/registry/index/
    - CargoHome/registry/cache/
    - src/rust/target/
    - src/rust/Cargo.lock

stages:
  - test

variables:
  GIT_DEPTH: 1

run_test:
  stage: test
  before_script:
    - git submodule update --init sqlcipher zstd
    - npm config set registry https://registry.npmmirror.com
    - npm install --save-dev @commitlint/config-conventional @commitlint/cli
  script:
    - export CARGO_HOME=${CI_PROJECT_DIR}/CargoHome
    - export RUSTFLAGS="-D warnings -A unused -A deprecated"
    - cd src/rust
    - echo "${CI_COMMIT_MESSAGE}" | npx commitlint
    - autocorrect --lint
    - FILES=$(git ls-files '*.c' '*.cpp' '*.h')
    - for file in $FILES; do
        clang-format "$file" | colordiff -u "$file" -;
      done
    - cargo fmt -- --check
    - cargo test -p wcdb_rust -- --test-threads=1
    - TARGET_SIZE=$(du -sm target 2>/dev/null | awk '{print $1}')
    - echo "target:${TARGET_SIZE}m"
    - if [ "$TARGET_SIZE" -gt 2048 ]; then
        rm -rf target;
      fi
