image: "harbor.rongcloud.net/library/rust/wcdb:0.0.4"

cache:
  paths:
    - CargoHome/registry/index/
    - CargoHome/registry/cache/
    - src/rust/target/
    - src/rust/Cargo.lock

stages:
  - test

variables:
  GIT_DEPTH: 1

run_test:
  stage: test
  before_script:
    - git submodule update --init sqlcipher zstd
  script:
    - export CARGO_HOME=${CI_PROJECT_DIR}/CargoHome
    - export RUSTFLAGS="-D warnings -A unused -A deprecated"
    - cd src/rust
    - autocorrect --lint
    - cargo fmt -- --check
    - cargo run --package wcdb_rust --example demo
