[package]
name = "table_binding_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.90", features = ["extra-traits"] }
proc-macro2 = "1.0.92"
quote = "1.0.37"
