[package]
name = "wcdb_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.90", features = ["full", "extra-traits"] }
proc-macro2 = "1.0.92"
quote = "1.0.37"
darling = "0.20.10"
once_cell = "1.19.0"
