[package]
name = "wcdb"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
num-derive = "0.4"
num-traits = "0.2"
libc = "1.0.0-alpha.1"
paste = "1.0.15"

[build-dependencies]
num_cpus = "1.16.0"
cmake = "0.1.52"
