#!/bin/bash  
  
root=`git rev-parse --show-toplevel`

format=$root/tools/format

for file in `git diff-index --cached --diff-filter=ACMRT --name-only HEAD` ; do  
    fullpath="$root/$file"
    if ! sh "$format/license.sh" --path "$fullpath"; then
        exit 1
    fi
    if ! sh "$format/code.sh" --path "$fullpath"; then
        exit 1
    fi
    git add "$fullpath"
done  
